http:
  middlewares:
    # Middleware to redirect non-canonical hosts to the canonical domain
    redirect-to-canonical:
      redirectRegex:
        regex: "^https?://(?:${IP}|127\\.0\\.0\\.1)(.*)"
        replacement: "https://${DOMAIN}$$1"
        permanent: true

  routers:
    # Default router to redirect HTTP to HTTPS
    default-redirect:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop-service # A dummy service is required for this router

  middlewares:
    # Middleware to enforce HTTPS redirection
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

services:
  # Noop service as Traefik requires a service for routers
  noop-service:
    loadBalancer:
      servers:
        - url: "http://127.0.0.1" 